spring:
  datasource:
    url: jdbc:mysql://cockple-mysql:3306/cockple?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: cockple-redis
      database: 0
